# LinkSOS NVIDIA Boot Entry
title   LinkSOS Linux (Live - NVIDIA)
linux   /arch/boot/x86_64/vmlinuz-linux-zen
initrd  /arch/boot/x86_64/initramfs-linux-zen.img
options archisobasedir=arch archisolabel=LINKSOS_%Y%m quiet splash loglevel=3 nvidia-drm.modeset=1 nvidia nvidia_modeset nvidia_uvm nvidia_drm
