# LinkSOS Verbose Boot Entry
title   LinkSOS Linux (Live - Verbose)
linux   /arch/boot/x86_64/vmlinuz-linux-zen
initrd  /arch/boot/x86_64/initramfs-linux-zen.img
options archisobasedir=arch archisolabel=LINKSOS_%Y%m loglevel=7
